;; (let ((numbers (upto 1 20)))
;;   (print (string-concat '("sum of " (inspect numbers) " is:")))
;;   (pp (sum numbers))
;;   (print (string-concat '("product of " (inspect numbers) " is:")))
;;   (pp (product numbers)))

(let* ((x 2)
       (y (* x 4))
       (z (/ (float y) 3)))
  (print- "x: ")
  (print x)
  (print- "y: ")
  (print y)
  (print- "z: ")
  (print z))